# Generated by Django 4.2.11 on 2024-03-19 05:16

import createapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maimltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.IntegerField(default=0, verbose_name='Model type')),
                ('type_name', models.TextField(verbose_name='Model Name')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('upload_maiml_id', models.UUIDField(default='88aff11e-a38c-4e65-b3d1-e62a76fbd75f', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upload_maiml', models.FileField(upload_to=createapp.models.path_branch)),
                ('upload_tiff', models.FileField(blank=True, upload_to=createapp.models.path_branch)),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('MaiMLtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='createapp.maimltype', verbose_name='protocolFileRootType')),
            ],
        ),
    ]
