# Generated by Django 5.0.6 on 2024-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='register_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
